import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import { project, title, ValidSubcategory } from '../../../util/parsed';
import Head from 'next/head';


import { Box } from 'react-feather'


const TabPage: NextPage = () => {
    const route = useRouter();
    return <>
        <Head>
            <title>{`${title} : ${route.query.category}`}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="flex w-full h-full overflow-y-auto bg-background rounded-br-md">

        </div>
    </>
}

export default TabPage;