import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import Head from 'next/head';
import { Sidebar } from 'react-feather'

import CategoryContent from '../../../../components/content/CategoryPage'
import clear_label from '../../../../util/clear_label'


const CategoryPage: NextPage = () => {
    const route = useRouter();
    
    return <>
        <Head>
            <title>{`${route.query.category}`}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="flex flex-col w-full h-full overflow-y-auto bg-background rounded-br-md">
            <div className="flex flex-col w-full h-full bg-background rounded-br-md ">
                <div className="border-b-2 border-white align-center border-opacity-5 ">
                    <div className="flex flex-row items-center px-4 text-white">
                        <Sidebar className="mr-4" />
                        <div className="flex flex-col w-full py-4 text-lg text-bold">
                            {clear_label(String(route.query.category))}<span className="-mt-1 text-sm text-white text-opacity-10">{route.query.tab}</span>
                        </div>
                    </div>
                </div>
            <CategoryContent />
            </div>  
        </div>
    </>
}

export default CategoryPage;